Handle invalid name of hook file

diff --git a/spawn_android b/spawn_android
--- a/spawn_android
+++ b/spawn_android
@@ -96,11 +96,16 @@ spawn_with_hook() {
 
 	read -p "[+] Please enter path to the hook JS file: " hook
 
-	printf "%s\n" "${delimiter}"
-	printf "[+] Spawning process %s with hook %s\n" "${process_name}" "${hook}"
-	printf "%s\n" "${delimiter}"
+	if ! [[ -f "${hook}" ]]
+	then
+		printf "[+] File %s not found\n" "${hook}"
+	else
+		printf "%s\n" "${delimiter}"
+		printf "[+] Spawning process %s with hook %s\n" "${process_name}" "${hook}"
+		printf "%s\n" "${delimiter}"
 
-	uv run frida -U -f "${process_name}" -l "${hook}" | tee "${frida_output_log}"
+		uv run frida -U -f "${process_name}" -l "${hook}" | tee "${frida_output_log}"
+	fi
 }
 
 spawn_without_hook() {
